#!/bin/sh#
# /etc/init.d/connect4Upi
# Subsystem file for "Connect4U pi server"
#
# chkconfig: 2345 95 05
# description: Connect4U pi server daemon
#
# processname: MySystem
# pidfile: /var/run/connect4Upi.pid

# source function library
. /etc/rc.d/init.d/functions

RETVAL=0
prog="Connect4UPi"

start() {
	echo -n $"Starting $prog:"
	sudo node /home/pi/pi/app.js
	RETVAL=$?
	[ "$RETVAL" = 0 ] && touch /var/lock/subsys/$prog
	echo
}

stop() {
	echo -n $"Stopping $prog:"
	killproc $prog -TERM
	RETVAL=$?
	[ "$RETVAL" = 0 ] && rm -f /var/lock/subsys/$prog
	echo
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	status)
		status $prog
		RETVAL=$?
		;;
	*)
		echo $"Usage: $0 {start|stop|restart|status}"
		RETVAL=1
esac
exit $RETVAL
